#!/bin/bash
#
# Script to backup a file or dir to a remote location

set -e          # stop on errors
set -u          # stop on unset variables
set -o pipefail # stop on pipe failures

usage(){
  echo "Usage: $(basename "$0") alert_webhookid service file|dir recipient"
}

E_NOARGS=85
wh_regex="T\w*\/B\w*\/\w*"
# TODO check recipient available in pgp keyservers?
if [ -z ${1+x} ] || [ -z ${2+x} ] || [ -z ${3+x} ] || [ -z ${4+x} ]; then
  usage
  exit "$E_NOARGS"
elif ! [[ $1 =~ $wh_regex ]]; then
  echo "Webhook format invalid. Expected format $wh_regex. Received: $1"
  usage
  exit 1
elif ! test -e "$3"; then
  echo "Cannot access file|dir: $3"
  usage
  exit 1
fi

wh=$1
service=$2
fileordir=$3
recipient=$4
now=$(date +%d%m%y-%H%M)

if test -d "$fileordir"; then
  tar_file="/tmp/${fileordir##*/}.tar.gz"
  parent=$(dirname "$fileordir")
  cd "$parent"
  sudo tar -czf "${tar_file}" "${fileordir##*/}"
  cd - > /dev/null
  fileordir="${tar_file}"
fi
file_enc="${fileordir##*/}-${now}.gpg"

path_enc="/tmp/${file_enc}"
gpg --quiet --encrypt --output "${path_enc}" --yes --recipient "${recipient}" "${fileordir}"

if [ "${service}" == "transfer.sh" ]; then
    backup_url=$(curl --silent --upload-file "${path_enc}" "https://transfer.sh/${file_enc}")
elif [ "${service}" == "filebin" ]; then
    bin_name="soydonchoco"
    upload_url="https://filebin.net/${bin_name}/${file_enc}"
    response_code=$(curl -X 'POST' -s -o /dev/null -w "%{http_code}" "${upload_url}" -H 'accept: application/json' -H 'Content-Type: application/octet-stream' --data-binary "@${path_enc}")
    if [ "${response_code}" == "201" ]; then
      backup_url="${upload_url}"
    else
      backup_url=""
    fi
else
    echo "Unknown service. Currently available: transfer.sh|filebin"
    exit 1
fi

# deleting temporary file
rm "$path_enc"

if [[ "${backup_url}" == *"${service}"* ]]; then
    echo "Backup performed - OK"
    echo "Backup url: ${backup_url}"
else
    webalert_hook="https://hooks.slack.com/services/$wh"
    echo "$(date) - $(basename "$0") - Backup not performed"
    content="{\"text\":\"\`$(hostname)\` - Backup failed \nResponse:\`${backup_url}\` \n \"}"
    echo "$(date) - $(basename "$0") - Calling webhook curl -s -X POST -H Content-type: application/json --data \"${content}\" \$webalert_hook"
    echo "$(date) - $(basename "$0") - Webhook result: $(curl -s -X POST -H 'Content-type: application/json' --data "${content}" "$webalert_hook")"
fi
