#!/bin/bash
# 
# Script to update home-assistant

set -e          # stop on errors
set -u          # stop on unset variables
set -o pipefail # stop on pipe failures

echo "[$(date)] home assistant update started"
docker pull ghcr.io/home-assistant/home-assistant:stable
source stop_run_ha
# to check next time this fails -- see if mounted volume is actually mounted
# docker inspect -f '{{ .Mounts }}' home-assistant