---
# Internet Speed Monitoring for Pi-hole Host
# Production implementation of speed monitoring with appropriate thresholds

- name: Load required variables and install Speedtest CLI on Pi-hole
  hosts: all
  vars_files:
    - "{{ playbook_dir }}/../../group_vars/all.yaml"
    - "{{ playbook_dir }}/../../group_vars/all_secrets.yaml"
  tasks:
    - name: Set the host fact to inventory_hostname
      ansible.builtin.set_fact:
        host: "{{ inventory_hostname }}"

- name: Install Ookla Speedtest CLI on Pi-hole
  ansible.builtin.import_playbook: "{{ playbook_dir }}/../../common_playbooks/install_speedtest.yml"

- name: Setup Internet Speed Monitoring on Pi-hole
  ansible.builtin.import_playbook: "{{ playbook_dir }}/../../common_playbooks/setup_internet_speed_monitoring.yml"
  vars:
    speed_monitoring_name: "pihole_internet_speed"
    min_download_mbps: 250        # Production threshold for download speed
    min_upload_mbps: 200           # Production threshold for upload speed
    max_ping_ms: 60             # Production threshold for ping latency
    speed_check_schedule: "0 */6 * * *"  # Every 6 hours
    heartbeat_interval: "daily"
    notify_fixed: "true"
