---
- name: Install mpd and modify configs
  hosts: all
  vars:
    mpd_conf: "/etc/mpd.conf"
  tasks:
    # check if needed
    - name: Install mpd
      become: true
      ansible.builtin.apt:
        pkg:
          - mpd
    - name: Allowing any host to connect
      become: true
      ansible.builtin.replace:
        dest: "{{ mpd_conf }}"
        regexp: '^bind_to_address'
        replace: '#bind_to_address'

    - name: Enabling mdns announcement of the device
      become: true
      ansible.builtin.copy:
        dest: "{{ mpd_conf }}"
        mode: preserve
        content: |
          zeroconf_enabled "yes"
          zeroconf_name "hifipi-mpd"

    - name: Reset ssh connection
      ansible.builtin.meta: reset_connection

    - name: Take volume to max
      become: true
      ignore_errors: true
      block:
        - name: Take volume to max
          ansible.builtin.command: amixer sset 'Analogue',0 100%
          changed_when: false
        - name: Alsactl store mixer config
          ansible.builtin.command: alsactl store
          changed_when: false
