---
- name: Install needed packages
  hosts: all
  tasks:
    - name: Install packages
      become: true
      ansible.builtin.apt:
        pkg:
          - autoconf
          - automake
          - avahi-daemon
          - build-essential
          - libasound2-dev
          - libavahi-client-dev
          - libconfig-dev
          - libdaemon-dev
          - libpopt-dev
          - libssl-dev
          - libtool
          - xmltoman
          - alsa-utils
          - libsoxr-dev

    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: https://github.com/mikebrady/shairport-sync.git # noqa: latest
        dest: "/home/{{ ansible_user_id }}/shairport-sync"
        update: true

    - name: Build shairport
      become: true
      block:
        - name: Autoreconf
          ansible.builtin.command:
            chdir: "/home/{{ ansible_user_id }}/shairport-sync"
            cmd: autoreconf -i -f
          changed_when: false
        - name: Configure
          ansible.builtin.command:
            chdir: "/home/{{ ansible_user_id }}/shairport-sync"
            cmd: ./configure --with-alsa --with-avahi --with-ssl=openssl --with-systemd --with-metadata --with-soxr
          changed_when: false
        - name: Make and install
          ansible.builtin.command:
            chdir: "/home/{{ ansible_user_id }}/shairport-sync"
            cmd: make && makeinstall
          changed_when: false
