---
- name: Disable screen on boot
  ansible.builtin.import_playbook: ../common_playbooks/disable_screen.yml

- name: Install Docker
  ansible.builtin.import_playbook: "{{host}}/install_docker.yml"

- name: Install HomeAssistant
  ansible.builtin.import_playbook: "{{host}}/install_ha.yml"

- name: Copy required scripts
  hosts: all
  tasks:
    - name: Move update_ha script to ~/.scripts
      copy:
        src: "{{host}}/update_ha"
        dest: ~/.scripts/
        mode: '0755'

    - name: Move stop_run_ha script to ~/.scripts
      copy:
        src: "{{host}}/stop_run_ha"
        dest: ~/.scripts/
        mode: '0755'

# Import host-specific health checks and maintenance tasks for dockassist
- name: Import dockassist health checks and maintenance tasks
  ansible.builtin.import_playbook: "{{host}}/dockassist_health_and_maintenance.yml"