---
- name: Disable screen on boot
  ansible.builtin.import_playbook: ../common_playbooks/disable_screen.yml

- name: Install Pihole
  ansible.builtin.import_playbook: "{{host}}/install_pihole.yml"

- name: Install Unifi Controller
  ansible.builtin.import_playbook: "{{host}}/install_unifi.yml"

# Import host-specific health checks and maintenance tasks for pihole
- name: Import pihole health checks and maintenance tasks
  ansible.builtin.import_playbook: "{{host}}/pihole_health_and_maintenance.yml"

# Import internet speed monitoring for pihole
- name: Import internet speed monitoring for pihole
  ansible.builtin.import_playbook: "{{host}}/pihole_speed_monitoring.yml"
