---
# Configure system settings like locale, hostname, and hosts file
- name: Configure system settings
  hosts: all
  become: true
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all.yaml"
    - "{{ playbook_dir }}/../group_vars/all_secrets.yaml"
  tasks:
    - name: Ensure the locale exists
      community.general.locale_gen:
        name: "{{ locale }}"
        state: present

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ host }}"

    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: '127.0.1.1       {{ host }}'
        state: present

    - name: Set vim.basic as default editor
      ansible.builtin.alternatives:
        name: editor
        path: /usr/bin/vim.basic
