---
# Configure system settings like locale, hostname, and hosts file
- name: Configure system settings
  hosts: all
  become: true
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all.yaml"
    - "{{ playbook_dir }}/../group_vars/all_secrets.yaml"
  tasks:
    - name: Ensure the locale exists
      community.general.locale_gen:
        name: "{{ locale }}"
        state: present

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ host }}"

    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: '127.0.1.1       {{ host }}'
        state: present

    - name: Set vim as default editor if available
      ansible.builtin.alternatives:
        name: editor
        path: /usr/bin/vim
      register: vim_result
      ignore_errors: true

    - name: Set vim.basic as default editor if vim is not available
      ansible.builtin.alternatives:
        name: editor
        path: /usr/bin/vim.basic
      register: vim_basic_result
      when: vim_result.failed
      ignore_errors: true

    - name: Set vim.tiny as default editor if vim and vim.basic are not available
      ansible.builtin.alternatives:
        name: editor
        path: /usr/bin/vim.tiny
      when: vim_result.failed and (vim_basic_result is defined and vim_basic_result.failed)
