---
- name: Create script folder and move scripts playbook
  hosts: all
  vars_files:
    - "{{ playbook_dir }}/../group_vars/all.yaml"
    - "{{ playbook_dir }}/../group_vars/all_secrets.yaml"
  tasks:
    - name: Creates script dir
      ansible.builtin.file:
        path: "{{ scripts_dir }}"
        mode: "0700"
        state: directory
    # Copying common files
    - name: Copy content of common to scripts files
      ansible.builtin.copy:
        src: ../common_scripts/
        dest: "{{ scripts_dir }}/"
        mode: preserve
        backup: true
        force: true
