---
- name: Disable bluetooth playbook
  hosts: all
  become: true
  tasks:
    - name: Disable Bluetooth related services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
      with_items:
        - hciuart.service
        - bluetooth.service
      ignore_errors: true
