---
- name: Uodate and upgrade all packages playbok
  hosts: all
  become: true
  tasks:
    - name: Update apt repo and cache on all raspbian boxes
      ansible.builtin.apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      ansible.builtin.apt: upgrade=dist force_apt_get=yes