---
- name: Full update, upgrade and clean playbook
  hosts: all
  become: true
  tasks:
    - name: Update apt repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
    - name: Apt autoremove autoclean and clean application
      ansible.builtin.apt:
        autoremove: true
        autoclean: true
        clean: true
